import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '../components/Navbar'
import GoogleChart from '../components/GoogleChart'
import Trade_top from '../components/Trade_top'
import Trading_down from '../components/Trading_down'
import { useState,useEffect } from 'react'
import { Alert } from "@mui/material";
import { sizeHeight } from '@mui/system'

const inter = Inter({ subsets: ['latin'] })
const win = "Winner"

const tradingpage = () => {

  const [Result, setResult] = useState(false)
  const [Insights, setInsights] = useState("")

  useEffect(() => {
    let result = localStorage.getItem('result')
    const insights = localStorage.getItem('insights')
    if(result == "false")
    {
      result = false
    }
    else{
      result = true
    }
    setResult(result)
    setInsights(insights)
  }, [])
  
  console.log(Result,Insights)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900 h-max">
        <Navbar/>
        <Trade_top/>
        <GoogleChart/>
        <div className="w-screen flex justify-center items-center">
          <Trading_down/>
        </div>
      </main>
    </>
  )
}

export default tradingpage
